### ISSUE TITLE
Bug: 절전모드 이후 플레이어 정지

### ISSUE THREAD

**Issue by moreal** [kosslab-kr/Presto.Contributhon#31]
윈도우10 환경에서 절전모드(노트북)를 거치고 오면 Presto 플레이어가 작동을 하지 않습니다

#bug #error

**Comment by iodes** [comment]
코어 사운드 엔진쪽 오류인 것 같습니다.
@SteaI 확인 및 처리 부탁드립니다.

**Comment by iodes** [comment]
문제 확인 및 해결을 완료했습니다.
1.0.0.1 버전 배포시 포함됩니다.
