### ISSUE TITLE
vuejs질문] refs를 이용한 컴포넌트의 메소드 외부 접근

### ISSUE THREAD

**Issue by youngdo212** [kosslab-kr/Presto.Contributhon#35]
$refs를 이용해 하위 컴포넌트의 메소드를 실행시키는 경우도 있나요?

**PlayerWrap에서 player를 실행시켜야 할 경우**
```
// PlayerWrap.vue
this.$refs.player.play(music)
```

**Comment by youngdo212** [comment]
$refs의 남용은 좋지 않다고 알고 있는데
refs를 이용하지 않고 하위 컴포넌트의 메소드를 실행시키는 방법이 있나요?

**Comment by Web-Engine** [comment]
ref를 쓰는건 잘못된 방법이 아닙니다. 메소드를 호출할 일이 있다면 충분히 사용해도 괜찮습니다.
http://vuejs.kr/jekyll/update/2017/03/13/vuejs-component-style-guide/#thisrefs%EB%A5%BC-%EC%A3%BC%EC%9D%98%ED%95%98%EC%97%AC-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

이 내용을 읽어보시면 도움이 될 것 같습니다.
ref를 통해 메소드를 호출하는 것 자체는 문제가 되지 않습니다.

ref를 남용한다는 것은 주로 하위 컴포넌트의 data에 접근할 때의 문제입니다.

**Comment by iodes** [comment]
문제 해결되었으므로,
이슈 닫도록 하겠습니다.
