### ISSUE TITLE
음악 상태의 변경시 발생하는 이벤트 형태

### ISSUE THREAD

**Issue by youngdo212** [kosslab-kr/Presto.Contributhon#36]
음악의 position이나 volume의 변경시에 발생하는 이벤트가
OnProperyChanged로 통일되어 있는것 보다
onVolumeChanged, onPositionChenged 등 구분되어 있으면 더 좋지 않을까요?

**Comment by Web-Engine** [comment]
C# 내부에 이미 그러한 형태로 구현되어 있다보니, 같은 형식을 따르게 되었습니다.

Web SDK에서 PropertyChanged 이벤트를 받아 VolumeChanged, PositionChanged와 같은 형태로 바꾸어 이벤트를 보낼 수 있도록 래핑하는 작업을 시도해보겠습니다.

**Comment by iodes** [comment]
처리 감사합니다.
